<?php
/**
  * Controller generated by MVCPHPGenerator
  * Created by cblopez at https://github.com/cblopez/mvcphpgenerator  *
  * By default, all actions are divided by the possible existance of $_POST array.
  */

include __DIR__.'/../Functions/gatherData.php';


switch($_GET['action']){

	case 'add':
	if(!$_POST){
		//Fill
	} else {
		//Fill
	}
	break;

	case 'search':
	if(!$_POST){
		//Fill
	} else {
		//Fill
	}
	break;

	case 'delete':
	if(!$_POST){
		//Fill
	} else {
		//Fill
	}
	break;

}

