from constants import *

def generateController(entityName, actionList, absolute_output_path):
    '''
    Controller Generator given an entity name, an action list and the output path
    @Param entityName: Name of the controller
    @Param actionList: List of actions that the controller will support
    @Param absolute_output_path: Path where the hole output is going to be written
    '''

    entityName = entityName.lower()
    entityName = entityName.title()
    entityName = entityName.replace(" ", "_")

    controller = open(absolute_output_path + '/Controllers/' + entityName + "_Controller.php", 'w')

    controller.write('<?php' + EOL)
    controller.write('/**' + EOL)
    controller.write('  * Controller generated by MVCPHPGenerator' + EOL)
    controller.write('  * Created by cblopez at https://github.com/cblopez/mvcphpgenerator')
    controller.write('  *' + EOL)
    controller.write('  * By default, all actions are divided by the possible existance of $_POST array.' + EOL)
    controller.write('  */' + EOL)
    controller.write(EOL)
    controller.write('include __DIR__.\'/../Functions/gatherData.php\';' + EOL)
    controller.write(EOL)
    controller.write(EOL)
    controller.write('switch($_GET[\'action\']){' + EOL)
    controller.write(EOL)
    for action in actionList:
        controller.write(ST + 'case \'' + action + '\':' + EOL)
        controller.write(ST + 'if(!$_POST){' + EOL)
        controller.write(DT + '//Fill' + EOL)
        controller.write(ST + '} else {' + EOL)
        controller.write(DT + '//Fill' + EOL)
        controller.write(ST + '}' + EOL)
        controller.write(ST + 'break;' + EOL)
        controller.write(EOL)
    controller.write('}' + EOL)
    controller.write(EOL)

    controller.close()
